-- Schema for a basic Supabase-backed icon search logging table
-- Run this in your Supabase project's SQL editor to create the table from scratch.

CREATE TABLE IF NOT EXISTS public.searches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  query text NOT NULL,
  library text NOT NULL,
  searched_at timestamptz NOT NULL DEFAULT now()
);

-- Optional: table to store favourite icons or search results
CREATE TABLE IF NOT EXISTS public.favourites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icon_id text NOT NULL,
  library text NOT NULL,
  added_at timestamptz NOT NULL DEFAULT now()
);

-- Generated icons storage
CREATE TABLE IF NOT EXISTS public.generated_icons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deterministic_id text NOT NULL, -- sha256(icon_name|image_url) for idempotency
  icon_name text NOT NULL,
  subject text NOT NULL,
  context text NOT NULL,
  style text NOT NULL,
  colors text NOT NULL,
  background text NOT NULL,
  image_url text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT generated_icons_deterministic_id_unique UNIQUE (deterministic_id)
);

-- Helpful indexes
CREATE INDEX IF NOT EXISTS generated_icons_created_at_idx ON public.generated_icons (created_at DESC);
CREATE INDEX IF NOT EXISTS generated_icons_subject_idx ON public.generated_icons (subject);
CREATE INDEX IF NOT EXISTS generated_icons_context_idx ON public.generated_icons (context);
CREATE INDEX IF NOT EXISTS generated_icons_style_idx ON public.generated_icons (style);
CREATE INDEX IF NOT EXISTS generated_icons_colors_idx ON public.generated_icons (colors);
CREATE INDEX IF NOT EXISTS generated_icons_background_idx ON public.generated_icons (background);

-- View reflecting current schema (context appended last to avoid rename issues)
CREATE OR REPLACE VIEW public.generated_icons_view AS
SELECT id, deterministic_id, icon_name, subject, style, colors, background, image_url, created_at, context
FROM public.generated_icons;

-- RLS - TEMPORARILY DISABLED FOR TESTING
-- ALTER TABLE public.generated_icons ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'generated_icons' AND policyname = 'Allow read to all'
  ) THEN
    CREATE POLICY "Allow read to all" ON public.generated_icons FOR SELECT USING (true);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'generated_icons' AND policyname = 'Allow insert to anon'
  ) THEN
    CREATE POLICY "Allow insert to anon" ON public.generated_icons FOR INSERT WITH CHECK (true);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'generated_icons' AND policyname = 'Allow update on conflict'
  ) THEN
    CREATE POLICY "Allow update on conflict" ON public.generated_icons FOR UPDATE USING (true) WITH CHECK (true);
  END IF;
END $$;