-- Schema for a basic Supabase-backed icon search logging table
-- Run this in your Supabase project's SQL editor to create the table.

CREATE TABLE IF NOT EXISTS public.searches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  query text NOT NULL,
  library text NOT NULL,
  searched_at timestamptz NOT NULL DEFAULT now()
);

-- Optional: table to store favourite icons or search results
CREATE TABLE IF NOT EXISTS public.favourites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icon_id text NOT NULL,
  library text NOT NULL,
  added_at timestamptz NOT NULL DEFAULT now()
);