-- Disable RLS on generated_icons table to allow public access to all generated icons
-- This allows all users to see icons generated by any user

-- Drop any existing policies first
DROP POLICY IF EXISTS "Users can insert their own generated icons" ON generated_icons;
DROP POLICY IF EXISTS "Users can view their own generated icons" ON generated_icons;
DROP POLICY IF EXISTS "Users can view all generated icons" ON generated_icons;
DROP POLICY IF EXISTS "Allow public read access to generated icons" ON generated_icons;

-- Disable RLS completely
ALTER TABLE generated_icons DISABLE ROW LEVEL SECURITY;

-- Grant public read access
GRANT SELECT ON generated_icons TO anon;
GRANT SELECT ON generated_icons TO authenticated;

-- Keep insert permissions for authenticated users
GRANT INSERT ON generated_icons TO authenticated;